version: 2
updates:
  # Enable version updates for Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 10
    reviewers:
      - "zots0127"
    assignees:
      - "zots0127"
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "deps"
      prefix-development: "deps(dev)"
      include: "scope"
    # 只更新 io 包到最新版本
    allow:
      - dependency-name: "github.com/zots0127/io"
        dependency-type: "all"
    # 其他依赖保持保守更新
    ignore:
      # 忽略主要版本更新
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "zots0127"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"